In [55]:
import requests
# fetch the web page
page = requests.get('https://oeis.ucf.edu/buildings')

#//print(page.content)

In [56]:
print(type(page.content))

<class 'bytes'>

In [57]:
from bs4 import BeautifulSoup

In [58]:
# turn page into a BeautifulSoup object
soup = BeautifulSoup(page.content, 'lxml')

In [59]:

#Find all the columns of the data set
dColumns = [] 
for th in soup.find_all('th'):
  dColumns.append(th.string.strip())

In [60]:
dColumns

['Name', 'Number', 'Type', 'Area (sqft)', 'EUI (kBTU/sqft)', 'LEED']

In [61]:
names = []
for a in soup.find_all('a', class_='')[0:]:
  names.append(a.string)
names

[' Alpha Delta Pi ',
 ' Alpha Tau Omega ',
 ' Alpha Xi Delta ',
 ' AMPAC Research Facility ',
 ' Ara Dr. Research Facility ',
 ' Arboretum Greenhouse ',
 ' Arboretum Portable ',
 ' Arts & Humanities Annex ',
 ' Barbara Ying Center ',
 ' Barbara Ying Center - CMMS ',
 ' Biological Sciences Building ',
 ' Biological Transgenic Greenhouse ',
 ' Biology Field Research Center ',
 ' Brevard Hall ',
 ' Burnett Honors College ',
 ' Burnett House ',
 ' Business Administration I ',
 ' Business Administration II ',
 ' Career Services & Experiential Learning ',
 ' CFE Federal Credit Union Arena ',
 ' Chemistry Building ',
 ' Chi Omega ',
 ' Citrus Hall ',
 ' Classroom Building I ',
 ' Classroom Building II ',
 ' Colbourn Hall ',
 ' College of Sciences Building ',
 ' Counseling and Psychological Services ',
 ' Creative School for Children 1 ',
 ' CREOL Building ',
 ' Delta Delta Delta ',
 ' Duke Energy University Welcome Center ',
 ' Early Childhood Center ',
 ' Education Complex & Gym ',
 ' Emergency Operation Center ',
 ' Engine Research Lab ',
 ' Engineering I ',
 ' Engineering II ',
 ' Facilities and Safety ',
 ' Fairwinds Alumni Center ',
 ' Flagler Hall ',
 ' Fraternity and Sorority Life ',
 ' Global UCF ',
 ' Harris Corporation Engineering Center ',
 ' Health & Public Affairs I ',
 ' Health & Public Affairs II ',
 ' Health Center ',
 ' Hercules Building 108 ',
 ' Hercules Building 109 ',
 ' Hercules Building 110 ',
 ' Hercules Building 111 ',
 ' Hercules Building 113 ',
 ' Housing Administration Building ',
 ' Housing Administrative Services ',
 ' Howard Phillips Hall ',
 ' Jay Bergman Field ',
 ' Jimmie A. Ferrell Student Services Commons ',
 ' John C. Hitt Library ',
 ' John T. Washington Center ',
 ' Kappa Alpha Theta ',
 ' Kappa Delta ',
 ' Kappa Kappa Gamma ',
 ' Kappa Sigma ',
 ' Kiosk ',
 ' Knights Plaza - Retail 2 ',
 ' Knights Plaza - Retail 3 ',
 ' Knights Plaza I ',
 ' Laboratory and Environmental Support ',
 ' Lake Claire Building 58 ',
 ' Lake Claire Building 65 ',
 ' Lake Claire Building 68 ',
 ' Lake Claire Pavilion 1 ',
 ' Lake Hall ',
 ' Leisure Pool Services ',
 ' Libra Community Center ',
 ' Libra Garage ',
 ' Mathematical Sciences Building ',
 ' Millican Hall ',
 ' MMAE Lab ',
 ' Morgridge International Reading Center ',
 ' Neptune Building 156 ',
 ' Neptune Building 157 ',
 ' Neptune Building 158 ',
 ' Nicholson Field House ',
 ' Nicholson School of Communication ',
 ' Nike Building 101 ',
 ' Nike Building 102 ',
 ' Nike Building 103 ',
 ' Nike Building 104 ',
 ' Nike Building 106 ',
 ' Orange Co. Schools Systems ',
 ' Orange Hall ',
 ' Osceola Hall ',
 ' Parking Garage - A ',
 ' Parking Garage - B ',
 ' Parking Garage - E ',
 ' Parking Garage - H ',
 ' Parking Garage C ',
 ' Parking Garage D ',
 ' Parking Garage F ',
 ' Parking Garage I ',
 ' Performing Arts Center ',
 ' Physical Sciences Building ',
 ' Pi Beta Phi ',
 ' Polk Hall ',
 ' Print Shop ',
 ' Psychology Building ',
 ' Public Safety Building ',
 ' Rec Services ',
 ' Recreation & Wellness Center ',
 ' Recreation Services Field Maintenance ',
 ' Recreation Support Building ',
 ' Rehearsal Hall ',
 ' Research I ',
 ' Robinson Observatory ',
 ' Scholarship House ',
 ' Seminole Hall ',
 ' Siemens Energy Center ',
 ' Sigma Chi ',
 ' Softball Stadium ',
 ' Spectrum Stadium ',
 ' Stormwater Research Lab ',
 ' Student Union ',
 ' Sumter Hall ',
 ' Teaching Academy ',
 ' Technology Commons I ',
 ' Technology Commons II ',
 ' Theatre ',
 ' Theta Chi ',
 ' Tower 1 ',
 ' Tower 2 ',
 ' Tower 3 ',
 ' Tower 4 ',
 ' Track / Soccer Stadium ',
 ' Trevor Colbourn Hall ',
 ' Visitor and Parking Information ',
 ' Visual Arts Building ',
 ' Volusia Hall ',
 ' Wayne Densch 1 ',
 ' Wayne Densch 2 ',
 ' Wayne Densch Center for Student-Athlete Leadership ',
 ' Wayne Densch Sports Center ',
 ' Zeta Tau Alpha ',
 '3546 South Perseus Loop Orlando, FL 32816-3644',
 'energy@ucf.edu',
 '407.823.2000']

In [62]:
""" scraping by navigating through elements eg: div.span.string """
# budget
rawdata = []
for td in soup.find_all('td'):
  rawdata.append(td.string)

In [63]:
rawdata

[None,
 '406',
 'Residence Hall',
 '5477',
 '270.56',
 None,
 None,
 '410',
 'Residence Hall',
 '10000',
 '61.7',
 None,
 None,
 '404',
 'Residence Hall',
 '5200',
 '534.42',
 None,
 None,
 '152',
 'Research',
 '7432',
 '276.4',
 None,
 None,
 '117',
 'Research',
 '2720',
 '375.14',
 None,
 None,
 '161',
 'Other',
 '1013',
 None,
 None,
 None,
 '525',
 'Office',
 '1440',
 '594.37',
 None,
 None,
 '541',
 'Classroom',
 '5376',
 '48.57',
 None,
 None,
 '71',
 'Office',
 '5789',
 '136.44',
 None,
 None,
 '81',
 'Classroom',
 '23685',
 '144.91',
 None,
 None,
 '20',
 'Research',
 '116607',
 '546.32',
 None,
 None,
 '124',
 'Research',
 '6111',
 '52.23',
 None,
 None,
 '92',
 'Research',
 '8000',
 '40.5',
 None,
 None,
 '30',
 'Residence Hall',
 '27926',
 '57.86',
 None,
 None,
 '95',
 'Classroom',
 '22220',
 '80.01',
 None,
 None,
 '100',
 'Residence Hall',
 '14393',
 '18.69',
 None,
 None,
 '45',
 'Classroom',
 '121074',
 '127.98',
 None,
 None,
 '94',
 'Classroom',
 '60809',
 '132.88',
 None,
 None,
 '140',
 'Office',
 '27000',
 '120.08',
 'Gold',
 None,
 '50',
 'Stadium',
 '370773',
 '134.4',
 None,
 None,
 '5',
 'Research',
 '49073',
 '466.44',
 None,
 None,
 '416',
 'Residence Hall',
 '13890',
 '50.54',
 'Gold',
 None,
 '85',
 'Residence Hall',
 '37100',
 '162.11',
 None,
 None,
 '79',
 'Classroom',
 '99380',
 '95.1',
 None,
 None,
 '98',
 'Classroom',
 '86250',
 '135.63',
 'Gold',
 None,
 '18',
 'Office',
 '83957',
 '103.72',
 None,
 None,
 '54',
 'Classroom',
 '54644',
 '436.29',
 None,
 None,
 '27',
 'Office',
 '15250',
 '203.85',
 None,
 None,
 '24',
 'Classroom',
 '5751',
 '64.68',
 None,
 None,
 '53',
 'Research',
 '111891',
 '495.11',
 'Gold',
 None,
 '403',
 'Residence Hall',
 '9470',
 '171.49',
 None,
 None,
 '96',
 'Office',
 '18717',
 '172.89',
 None,
 None,
 '28',
 'Classroom',
 '3627',
 '109.73',
 None,
 None,
 '21',
 'Classroom',
 '110272',
 '198.71',
 None,
 None,
 '49',
 'Office',
 '7043',
 '85.88',
 None,
 None,
 '76',
 'Research',
 '3569',
 '66.32',
 None,
 None,
 '40',
 'Classroom',
 '130885',
 '150.79',
 None,
 None,
 '91',
 'Classroom',
 '105545',
 '185.8',
 None,
 None,
 '16',
 'Office',
 '103286',
 '28.38',
 'Silver',
 None,
 '126',
 'Office',
 '26953',
 '161.67',
 'Gold',
 None,
 '86',
 'Residence Hall',
 '59200',
 '125.21',
 None,
 None,
 '415',
 'Residence Hall',
 '5662',
 '69.5',
 'Silver',
 None,
 '139',
 'Office',
 '52957',
 '73.47',
 'Gold',
 None,
 '116',
 'Classroom',
 '113866',
 '211.66',
 None,
 None,
 '80',
 'Classroom',
 '93897',
 '146.32',
 None,
 None,
 '90',
 'Classroom',
 '61904',
 '202.3',
 None,
 None,
 '127',
 'Office',
 '48392',
 '165.25',
 None,
 None,
 '108',
 'Residence Hall',
 '38686',
 '325.15',
 None,
 None,
 '109',
 'Residence Hall',
 '42731',
 '69.96',
 None,
 None,
 '110',
 'Residence Hall',
 '41617',
 '61.45',
 None,
 None,
 '111',
 'Residence Hall',
 '53130',
 '34.5',
 None,
 None,
 '113',
 'Residence Hall',
 '53130',
 '43.35',
 None,
 None,
 '73',
 'Office',
 '6675',
 '8.39',
 None,
 None,
 '159',
 'Office',
 '12769',
 '368.18',
 None,
 None,
 '14',
 'Office',
 '64619',
 '117.87',
 None,
 None,
 '82',
 'Stadium',
 '26944',
 '113.47',
 None,
 None,
 '7',
 'Office',
 '93860',
 '561.71',
 None,
 None,
 '2',
 'Other',
 '226506',
 '175.96',
 None,
 None,
 '26',
 'Retail',
 '59071',
 '124.66',
 None,
 None,
 '411',
 'Residence Hall',
 '11518',
 '68.45',
 None,
 None,
 '407',
 'Residence Hall',
 '4969',
 '353.19',
 None,
 None,
 '417',
 'Residence Hall',
 '13890',
 '53.78',
 'Gold',
 None,
 '413',
 'Residence Hall',
 '6000',
 '74.58',
 None,
 None,
 '310',
 'Retail',
 '283',
 '351.65',
 None,
 None,
 '138',
 'Retail',
 '15304',
 '1.86',
 None,
 None,
 '139',
 'Retail',
 '9045',
 '167.04',
 None,
 None,
 '137',
 'Retail',
 '31666',
 '159.72',
 None,
 None,
 '48',
 'Other',
 '9569',
 '84.82',
 'Gold',
 None,
 '58',
 'Residence Hall',
 '14652',
 '548.18',
 None,
 None,
 '65',
 'Residence Hall',
 '3788',
 '1514.78',
 None,
 None,
 '68',
 'Residence Hall',
 '14652',
 '3.07',
 None,
 None,
 '331',
 'Other',
 '2750',
 '982.8',
 None,
 None,
 '9',
 'Residence Hall',
 '24456',
 '204.05',
 None,
 None,
 '118',
 'Other',
 '5326',
 '208.44',
 None,
 None,
 '33',
 'Other',
 '4698',
 '2543.67',
 None,
 None,
 '160',
 'Parking Garage',
 '387638',
 '2.98',
 None,
 None,
 '12',
 'Classroom',
 '106523',
 '167.66',
 None,
 None,
 '1',
 'Office',
 '87742',
 '183.89',
 None,
 None,
 '154',
 'Research',
 '7867',
 '575.45',
 None,
 None,
 '122',
 'Office',
 '16726',
 '176.73',
 'Gold',
 None,
 '156',
 'Residence Hall',
 '60088',
 '62.88',
 'Silver',
 None,
 '157',
 'Residence Hall',
 '65359',
 '74.71',
 None,
 None,
 '158',
 'Residence Hall',
 '83379',
 '65.37',
 None,
 None,
 '128',
 'Stadium',
 '81337',
 '17.54',
 None,
 None,
 '75',
 'Classroom',
 '81576',
 '181.14',
 None,
 None,
 '101',
 'Residence Hall',
 '38686',
 '298.87',
 None,
 None,
 '102',
 'Residence Hall',
 '42731',
 '115.5',
 None,
 None,
 '103',
 'Residence Hall',
 '41617',
 '61.38',
 None,
 None,
 '104',
 'Residence Hall',
 '53130',
 '37.93',
 None,
 None,
 '106',
 'Residence Hall',
 '53130',
 '39.38',
 None,
 None,
 '546',
 'Office',
 '840',
 '7.14',
 None,
 None,
 '31',
 'Residence Hall',
 '37241',
 '75.55',
 None,
 None,
 '10',
 'Residence Hall',
 '24456',
 '292.92',
 None,
 None,
 '147',
 'Parking Garage',
 '487433',
 '2.59',
 None,
 None,
 '89',
 'Parking Garage',
 '387638',
 '8.64',
 None,
 None,
 '134',
 'Parking Garage',
 '387638',
 '1.19',
 None,
 None,
 '151',
 'Parking Garage',
 '400200',
 '8.18',
 None,
 None,
 '83',
 'Parking Garage',
 '387638',
 '4.95',
 None,
 None,
 '97',
 'Parking Garage',
 '387638',
 '10.94',
 None,
 None,
 '141',
 'Parking Garage',
 '387638',
 '7.87',
 None,
 None,
 '78',
 'Parking Garage',
 '387638',
 '2.88',
 None,
 None,
 '119',
 'Classroom',
 '80942',
 '92.25',
 'Gold',
 None,
 '121',
 'Research',
 '128887',
 '514.56',
 'Gold',
 None,
 '405',
 'Residence Hall',
 '8450',
 '369.94',
 None,
 None,
 '11',
 'Residence Hall',
 '24456',
 '247.1',
 None,
 None,
 '22',
 'Retail',
 '12515',
 '3.72',
 None,
 None,
 '99',
 'Classroom',
 '76257',
 '89.65',
 None,
 None,
 '150',
 'Office',
 '36240',
 '178.17',
 'Gold',
 None,
 '15',
 'Office',
 '0',
 None,
 None,
 None,
 '88',
 'Office',
 '156111',
 '123.64',
 'Gold',
 None,
 '321',
 'Other',
 '3918',
 '17.71',
 None,
 None,
 '25',
 'Other',
 '3025',
 '1284.06',
 None,
 None,
 '19',
 'Office',
 '10743',
 '100.04',
 None,
 None,
 '120',
 'Research',
 '105775',
 None,
 'Gold',
 None,
 '74',
 'Other',
 '2070',
 '20.79',
 None,
 None,
 '402',
 'Office',
 '4038',
 '63.83',
 None,
 None,
 '32',
 'Residence Hall',
 '37241',
 '77.46',
 None,
 None,
 '44',
 'Research',
 '10932',
 '66.82',
 None,
 None,
 '412',
 'Residence Hall',
 '6000',
 None,
 None,
 None,
 '125',
 'Stadium',
 '6412',
 '140.44',
 None,
 None,
 '135',
 'Stadium',
 '76527',
 '183.53',
 None,
 None,
 '4',
 'Research',
 '2685',
 '34.9',
 None,
 None,
 '52',
 'Retail',
 '161755',
 '257.86',
 'Certified',
 None,
 '84',
 'Residence Hall',
 '59200',
 '147.34',
 None,
 None,
 '93',
 'Classroom',
 '68094',
 '163.99',
 None,
 None,
 '13',
 'Office',
 '10779',
 '100.65',
 None,
 None,
 '29',
 'Office',
 '33370',
 '118.85',
 None,
 None,
 '6',
 'Classroom',
 '29469',
 '83.62',
 None,
 None,
 '409',
 'Residence Hall',
 '13151',
 '89.1',
 None,
 None,
 '129',
 'Residence Hall',
 '200933',
 '91.3',
 None,
 None,
 '130',
 'Residence Hall',
 '200933',
 '70.31',
 None,
 None,
 '132',
 'Residence Hall',
 '187647',
 '150.9',
 None,
 None,
 '133',
 'Residence Hall',
 '200933',
 '78.32',
 None,
 None,
 '142',
 'Stadium',
 '1192',
 '68.52',
 None,
 None,
 '123',
 'Office',
 '136786',
 None,
 'Gold',
 None,
 '153',
 'Office',
 '2260',
 '79.31',
 'Silver',
 None,
 '51',
 'Classroom',
 '85000',
 '94.74',
 None,
 None,
 '8',
 'Residence Hall',
 '24456',
 '298.36',
 None,
 None,
 '38',
 'Office',
 '18860',
 '207.93',
 None,
 None,
 '39',
 'Office',
 '15876',
 '63.9',
 None,
 None,
 '136',
 'Classroom',
 '21657',
 '99.65',
 'Gold',
 None,
 '77',
 'Office',
 '45330',
 '210.64',
 None,
 None,
 '401',
 'Residence Hall',
 '10230',
 '176.22',
 None]

In [64]:
rawlen = len(rawdata)

In [65]:
import csv

In [66]:
""" writing data to CSV """
# open top25.csv file in "write" mode
with open('ucfenergy', 'w') as file:
  # create a "writer" object
  writer = csv.writer(file, delimiter=',')
  # use "writer" obj to write 
  # you should give a "list"
  writer.writerow(dColumns)                                                                                                                                                                                                        
  for i in range(rawlen):
    writer.writerow([
      rawdata[i], 

 ])

In [67]:
import os
import pandas as pd

In [68]:
nRawData = pd.read_csv(r'C:\Users\Zach\_Python Project\Ucf data scraper and analysis\ucfenergy')

In [69]:
nRawData = nRawData['Name']

In [70]:
nRawData

0                 NaN
1                 406
2      Residence Hall
3                5477
4              270.56
            ...
853               401
854    Residence Hall
855             10230
856            176.22
857               NaN
Name: Name, Length: 858, dtype: object

In [71]:
dColumns

['Name', 'Number', 'Type', 'Area (sqft)', 'EUI (kBTU/sqft)', 'LEED']

In [72]:
import numpy as np
arr = np.array(nRawData)

arr2 = np.reshape(arr, (143, 6)) # here (4, 4) are the number of rows and columns



rRawData = pd.DataFrame(arr2, columns = dColumns)
rRawData

    Name Number            Type Area (sqft) EUI (kBTU/sqft)  LEED
0    NaN    406  Residence Hall        5477          270.56   NaN
1    NaN    410  Residence Hall       10000            61.7   NaN
2    NaN    404  Residence Hall        5200          534.42   NaN
3    NaN    152        Research        7432           276.4   NaN
4    NaN    117        Research        2720          375.14   NaN
..   ...    ...             ...         ...             ...   ...
138  NaN     38          Office       18860          207.93   NaN
139  NaN     39          Office       15876            63.9   NaN
140  NaN    136       Classroom       21657           99.65  Gold
141  NaN     77          Office       45330          210.64   NaN
142  NaN    401  Residence Hall       10230          176.22   NaN

[143 rows x 6 columns]

In [73]:
len(names)

146

In [74]:
nameAdd = pd.DataFrame(names)

In [75]:
nameAdd = nameAdd.loc[0:142]

In [76]:
cleanDataA = pd.concat([nameAdd,rRawData], axis = 1)

In [77]:
cleanDataA = cleanDataA.drop(columns=['Name'])

In [78]:
cleanDataA = cleanDataA.rename(columns= {0: 'Building Name'})

In [79]:
cleanDataA

,Building Name,Number,Type,Area (sqft),EUI (kBTU/sqft),LEED
0,Alpha Delta Pi,406,Residence Hall,5477,270.56,NaN
1,Alpha Tau Omega,410,Residence Hall,10000,61.7,NaN
2,Alpha Xi Delta,404,Residence Hall,5200,534.42,NaN
3,AMPAC Research Facility,152,Research,7432,276.4,NaN
4,Ara Dr. Research Facility,117,Research,2720,375.14,NaN
...,...,...,...,...,...,...
138,Wayne Densch 1,38,Office,18860,207.93,NaN
139,Wayne Densch 2,39,Office,15876,63.9,NaN
140,Wayne Densch Center for Student-Athlete Leade...,136,Classroom,21657,99.65,Gold
141,Wayne Densch Sports Center,77,Office,45330,210.64,NaN
142,Zeta Tau Alpha,401,Residence Hall,10230,176.22,NaN

In [80]:
cleanDataA.to_csv ('ucfEnergyCleanDataA',index=None)

In [81]:
page2 = requests.get('https://oeis.ucf.edu/stats')

In [82]:
soup2 = BeautifulSoup(page2.content, 'lxml')

In [83]:
#Find all the columns of the data set
dColumns2 = [] 
for th in soup2.find_all('th', colspan = '2'):
  dColumns2.append(th.string.strip())

In [84]:
dColumns2

['Commodity', "FY '16-17", "FY '17-18", "FY '18-19", "FY '19-20"]

In [85]:
dRows2 = [] 
for th in soup2.find_all('th', colspan = ''):
  dRows2.append(th.string.strip())

In [86]:
dRows2

['Campus Size',
 'Enrollment',
 'Electricity Purchased',
 'Electricity Produced',
 'Natural Gas Purchased',
 'Chilled Water Produced',
 'Water Produced',
 'Water Purchased',
 'Wastewater Transported',
 'Reclaimed Water Purchased',
 'Green Power Produced',
 'Green Power Purchased']

In [87]:
# budget
rawdata2 = []
for td in soup2.find_all('td'):
  rawdata2.append(td.string)

In [88]:
rawdata2

['sqft',
 '10,158,618',
 '+1%',
 '10,320,473',
 '+2%',
 '10,461,034',
 '+1%',
 '10,243,104',
 '-2%',
 'students',
 '64,335',
 '+2%',
 '66,180',
 '+3%',
 '68,571',
 '+3%',
 '69,525',
 '+1%',
 'kWh',
 '104,970,402',
 '-12%',
 '106,877,814',
 '+2%',
 '114,428,160',
 '+7%',
 '108,231,201',
 '-5%',
 'kWh',
 '39,358,314',
 '+43%',
 '36,924,683',
 '-6%',
 '33,890,092',
 '-8%',
 '32,956,663',
 '-2%',
 'therms',
 '4,475,309',
 '+35%',
 '4,285,223',
 '-4%',
 '4,063,854',
 '-5%',
 '3,856,694',
 '-5%',
 'ton-hours',
 '38,333,540',
 '+2%',
 '38,393,397',
 '+.2%',
 '40,857,306',
 '+6%',
 '41,664,400',
 '+2%',
 'gal',
 '174,524,900',
 '-23%',
 '231,177,100',
 '+32%',
 '242,823,000',
 '+5%',
 '229,746,000',
 '-5%',
 'gal',
 '101,460,000',
 '+165%',
 '35,882,000',
 '-64%',
 '22,458,000',
 '-37%',
 '22,840,000',
 '+2%',
 'gal',
 '275,342,700',
 '+6%',
 '250,659,700',
 '-9%',
 '251,259,000',
 '+0.2%',
 '214,300,000',
 '-15%',
 'gal',
 '202,721,500',
 '+17%',
 '195,733,000',
 '-3%',
 '189,581,000',
 '-3%',
 '194,131,000',
 '+2%',
 'kWh',
 '151,113',
 '-4%',
 '111,131',
 '-27%',
 '100,875',
 '-9%',
 '134,892',
 '+34%',
 'kWh',
 '5,078,000',
 '+9%',
 '1,638,000',
 '-68%',
 '1,498,000',
 '-9%',
 '0',
 '-100%']

In [89]:
nRawData2 = pd.DataFrame (rawdata2)

In [90]:
nRawData2

              0
0          sqft
1    10,158,618
2           +1%
3    10,320,473
4           +2%
..          ...
103        -68%
104   1,498,000
105         -9%
106           0
107       -100%

[108 rows x 1 columns]

In [91]:
len(rawdata2)

108

In [92]:
arr = np.array(nRawData2)

arr2_2 = np.reshape(arr, (12, 9)) # here (4, 4) are the number of rows and columns



rRawData2 = pd.DataFrame(arr2_2,columns=['a','b','c','d','e','f','g','h','i'])
rRawData2

,a,b,c,d,e,f,g,h,i
0,sqft,"10,158,618",+1%,"10,320,473",+2%,"10,461,034",+1%,"10,243,104",-2%
1,students,"64,335",+2%,"66,180",+3%,"68,571",+3%,"69,525",+1%
2,kWh,"104,970,402",-12%,"106,877,814",+2%,"114,428,160",+7%,"108,231,201",-5%
3,kWh,"39,358,314",+43%,"36,924,683",-6%,"33,890,092",-8%,"32,956,663",-2%
4,therms,"4,475,309",+35%,"4,285,223",-4%,"4,063,854",-5%,"3,856,694",-5%
5,ton-hours,"38,333,540",+2%,"38,393,397",+.2%,"40,857,306",+6%,"41,664,400",+2%
6,gal,"174,524,900",-23%,"231,177,100",+32%,"242,823,000",+5%,"229,746,000",-5%
7,gal,"101,460,000",+165%,"35,882,000",-64%,"22,458,000",-37%,"22,840,000",+2%
8,gal,"275,342,700",+6%,"250,659,700",-9%,"251,259,000",+0.2%,"214,300,000",-15%
9,gal,"202,721,500",+17%,"195,733,000",-3%,"189,581,000",-3%,"194,131,000",+2%
10,kWh,"151,113",-4%,"111,131",-27%,"100,875",-9%,"134,892",+34%
11,kWh,"5,078,000",+9%,"1,638,000",-68%,"1,498,000",-9%,0,-100%

In [93]:
dRows2df = pd.DataFrame (dRows2,columns=['aa'])

In [94]:
nData2 = pd.concat([dRows2df,rRawData2], axis=1)

In [95]:
nData2

,aa,a,b,c,d,e,f,g,h,i
0,Campus Size,sqft,"10,158,618",+1%,"10,320,473",+2%,"10,461,034",+1%,"10,243,104",-2%
1,Enrollment,students,"64,335",+2%,"66,180",+3%,"68,571",+3%,"69,525",+1%
2,Electricity Purchased,kWh,"104,970,402",-12%,"106,877,814",+2%,"114,428,160",+7%,"108,231,201",-5%
3,Electricity Produced,kWh,"39,358,314",+43%,"36,924,683",-6%,"33,890,092",-8%,"32,956,663",-2%
4,Natural Gas Purchased,therms,"4,475,309",+35%,"4,285,223",-4%,"4,063,854",-5%,"3,856,694",-5%
5,Chilled Water Produced,ton-hours,"38,333,540",+2%,"38,393,397",+.2%,"40,857,306",+6%,"41,664,400",+2%
6,Water Produced,gal,"174,524,900",-23%,"231,177,100",+32%,"242,823,000",+5%,"229,746,000",-5%
7,Water Purchased,gal,"101,460,000",+165%,"35,882,000",-64%,"22,458,000",-37%,"22,840,000",+2%
8,Wastewater Transported,gal,"275,342,700",+6%,"250,659,700",-9%,"251,259,000",+0.2%,"214,300,000",-15%
9,Reclaimed Water Purchased,gal,"202,721,500",+17%,"195,733,000",-3%,"189,581,000",-3%,"194,131,000",+2%
10,Green Power Produced,kWh,"151,113",-4%,"111,131",-27%,"100,875",-9%,"134,892",+34%
11,Green Power Purchased,kWh,"5,078,000",+9%,"1,638,000",-68%,"1,498,000",-9%,0,-100%

In [96]:
nData2 = nData2.rename(columns={'aa':'Commodity', 'a':'Units','b': 'FY 16-17 Value','c': 'FY 16-17 % Change', 'd': 'FY 17-18 Value','e': 'FY 17-18 % Change', 'f': 'FY 18-19 Value','g': 'FY 18-19 % Change','h': 'FY 19-20 Value','i': 'FY 19-20 % Change'})

In [97]:
nData2

,Commodity,Units,FY 16-17 Value,FY 16-17 % Change,FY 17-18 Value,FY 17-18 % Change,FY 18-19 Value,FY 18-19 % Change,FY 19-20 Value,FY 19-20 % Change
0,Campus Size,sqft,"10,158,618",+1%,"10,320,473",+2%,"10,461,034",+1%,"10,243,104",-2%
1,Enrollment,students,"64,335",+2%,"66,180",+3%,"68,571",+3%,"69,525",+1%
2,Electricity Purchased,kWh,"104,970,402",-12%,"106,877,814",+2%,"114,428,160",+7%,"108,231,201",-5%
3,Electricity Produced,kWh,"39,358,314",+43%,"36,924,683",-6%,"33,890,092",-8%,"32,956,663",-2%
4,Natural Gas Purchased,therms,"4,475,309",+35%,"4,285,223",-4%,"4,063,854",-5%,"3,856,694",-5%
5,Chilled Water Produced,ton-hours,"38,333,540",+2%,"38,393,397",+.2%,"40,857,306",+6%,"41,664,400",+2%
6,Water Produced,gal,"174,524,900",-23%,"231,177,100",+32%,"242,823,000",+5%,"229,746,000",-5%
7,Water Purchased,gal,"101,460,000",+165%,"35,882,000",-64%,"22,458,000",-37%,"22,840,000",+2%
8,Wastewater Transported,gal,"275,342,700",+6%,"250,659,700",-9%,"251,259,000",+0.2%,"214,300,000",-15%
9,Reclaimed Water Purchased,gal,"202,721,500",+17%,"195,733,000",-3%,"189,581,000",-3%,"194,131,000",+2%
10,Green Power Produced,kWh,"151,113",-4%,"111,131",-27%,"100,875",-9%,"134,892",+34%
11,Green Power Purchased,kWh,"5,078,000",+9%,"1,638,000",-68%,"1,498,000",-9%,0,-100%

In [98]:
nData2.to_csv ('ucfEnergyCleanDataB',index=None)

In [99]:
page3 = requests.get('https://energy.ucf.edu/high-performance-buildings/')

In [100]:
# turn page into a BeautifulSoup object
soup3 = BeautifulSoup(page3.content, 'lxml')

In [101]:
#Find all the columns of the data set
dBuilding3 = [] 
for h4 in soup3.find_all('h4',class_ ='leed-name'):
  dBuilding3.append(h4.string.strip())

In [102]:
dBuilding3

['UCF Roth Athletic Center',
 'UCF Classroom I',
 'UCF Downtown: Central Energy Plant',
 'UCF Downtown: Dr. Phillips Academic Commons',
 'UCF Student Union Expansion',
 'UCF John C. Hitt Library Expansion',
 'UCF CREOL Expansion',
 'UCF Band Practice Facility',
 'UCF Dining Facility',
 'UCF Resource Management Warehouse',
 'UCF Trevor Colbourn Hall',
 'UCF District Energy Plant IV',
 'UCF Research I',
 'UCF Global',
 'UCF Alumni Center',
 'UCF Wayne Densch Center for Student-Athlete Leadership',
 'UCF Academic Village Phase II',
 'UCF Visitor and Parking Information',
 'UCF Classroom II',
 'UCF Physical Science II',
 'UCF Fraternity and Sorority Life',
 'UCF College of Medicine',
 'UCF Morgridge Intl Reading Center',
 'UCF Greek House A',
 'UCF Greek House B',
 'UCF Partnership III',
 'UCF Public Safety',
 'UCF Recreation & Wellness Expansion',
 'UCF Career Services',
 'UCF Performing Arts Center',
 'UCF Biomedical Science',
 'UCF Laboratory and Environmental Support',
 'UCF Physical Science']

In [103]:
dStat3 = [] 
for div in soup3.find_all('div',class_ ='leed-status'):
  dStat3.append(div.string.strip())

In [104]:
dStat3

['Registered',
 'Registered',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Certified®',
 'Registered',
 'LEED Gold®',
 'LEED Silver®',
 'LEED Certified®',
 'LEED Silver®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Silver®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Silver®',
 'LEED Silver®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Silver®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Gold®',
 'LEED Silver®',
 'LEED Gold®',
 'LEED Gold®']

In [105]:
#d3 = [] 
#for tr in soup3.find_all('tr', class_='recert'):
#  d3.append(tr)

In [106]:
import re

In [107]:
d4 = [] 
for td in soup3.find_all('td',text = re.compile('Certification')):
  d4.append(td)

In [108]:
d4

[<td colspan="2">Certification awarded Feb 2020</td>,
 <td colspan="2">Certification awarded October 2021</td>,
 <td colspan="2">Certification awarded June 2021</td>,
 <td colspan="2">Certification awarded Jan 2020</td>,
 <td colspan="2">Certification awarded Nov 2018</td>,
 <td colspan="2">Certification awarded July 2019</td>,
 <td colspan="2">Certification awarded May 2019</td>,
 <td colspan="2">Certification awarded Apr 2019</td>,
 <td colspan="2">Certification awarded Apr 2018</td>,
 <td colspan="2">Certification awarded Sept 2018</td>,
 <td colspan="2">Certification awarded Aug 2016</td>,
 <td colspan="2">Certification awarded Jan 2018</td>,
 <td colspan="2">Certification awarded Jun 2017</td>,
 <td colspan="2">Certification awarded Oct 2015</td>,
 <td colspan="2">Certification awarded Jul 2015</td>,
 <td colspan="2">Certification awarded Jul 2015</td>,
 <td colspan="2">Certification awarded Jun 2015</td>,
 <td colspan="2">Certification awarded May 2014</td>,
 <td colspan="2">Certification awarded Apr 2014</td>,
 <td colspan="2">Certification awarded Mar 2014</td>,
 <td colspan="2">Certification awarded Oct 2012</td>,
 <td colspan="2">Certification awarded Sep 2012</td>,
 <td colspan="2">Certification awarded Sep 2012</td>,
 <td colspan="2">Certification awarded Jul 2012</td>,
 <td colspan="2">Certification awarded Apr 2012</td>,
 <td colspan="2">Certification awarded Sep 2010</td>,
 <td colspan="2">Certification awarded Aug 2010</td>,
 <td colspan="2">Certification awarded Dec 2009</td>]

In [109]:
#d3

In [110]:
#dDf3 = pd.DataFrame(d3, dtype=object)

In [111]:
ddd = pd.DataFrame(d4)

In [112]:
ddd

                                     0
0       Certification awarded Feb 2020
1   Certification awarded October 2021
2      Certification awarded June 2021
3       Certification awarded Jan 2020
4       Certification awarded Nov 2018
5      Certification awarded July 2019
6       Certification awarded May 2019
7       Certification awarded Apr 2019
8       Certification awarded Apr 2018
9      Certification awarded Sept 2018
10      Certification awarded Aug 2016
11      Certification awarded Jan 2018
12      Certification awarded Jun 2017
13      Certification awarded Oct 2015
14      Certification awarded Jul 2015
15      Certification awarded Jul 2015
16      Certification awarded Jun 2015
17      Certification awarded May 2014
18      Certification awarded Apr 2014
19      Certification awarded Mar 2014
20      Certification awarded Oct 2012
21      Certification awarded Sep 2012
22      Certification awarded Sep 2012
23      Certification awarded Jul 2012
24      Certification awarded Apr 2012
25      Certification awarded Sep 2010
26      Certification awarded Aug 2010
27      Certification awarded Dec 2009

In [113]:
#dDf3

In [114]:
#dDf3 = dDf3[1]

In [115]:
#dDf3

In [116]:
dDf1 = pd.DataFrame(dBuilding3,columns=['BuildingName'])

In [117]:
#dDf1

#dBL = dDfX[dDfX['LEED Status'].str.contains('Registered') == False]

In [118]:
dDf2 = pd.DataFrame(dStat3,columns=['LEED Status'])

In [119]:
dDf2

        LEED Status
0        Registered
1        Registered
2        LEED Gold®
3        LEED Gold®
4   LEED Certified®
5        Registered
6        LEED Gold®
7      LEED Silver®
8   LEED Certified®
9      LEED Silver®
10       LEED Gold®
11       LEED Gold®
12       LEED Gold®
13       LEED Gold®
14       LEED Gold®
15       LEED Gold®
16     LEED Silver®
17       LEED Gold®
18       LEED Gold®
19       LEED Gold®
20     LEED Silver®
21     LEED Silver®
22       LEED Gold®
23       LEED Gold®
24       LEED Gold®
25     LEED Silver®
26       LEED Gold®
27       LEED Gold®
28       LEED Gold®
29       LEED Gold®
30     LEED Silver®
31       LEED Gold®
32       LEED Gold®

In [120]:
dDfX = pd.concat([dDf1,dDf2],axis=1)

In [121]:
dDfX

                                         BuildingName      LEED Status
0                            UCF Roth Athletic Center       Registered
1                                     UCF Classroom I       Registered
2                  UCF Downtown: Central Energy Plant       LEED Gold®
3         UCF Downtown: Dr. Phillips Academic Commons       LEED Gold®
4                         UCF Student Union Expansion  LEED Certified®
5                  UCF John C. Hitt Library Expansion       Registered
6                                 UCF CREOL Expansion       LEED Gold®
7                          UCF Band Practice Facility     LEED Silver®
8                                 UCF Dining Facility  LEED Certified®
9                   UCF Resource Management Warehouse     LEED Silver®
10                           UCF Trevor Colbourn Hall       LEED Gold®
11                       UCF District Energy Plant IV       LEED Gold®
12                                     UCF Research I       LEED Gold®
13                                         UCF Global       LEED Gold®
14                                  UCF Alumni Center       LEED Gold®
15  UCF Wayne Densch Center for Student-Athlete Le...       LEED Gold®
16                      UCF Academic Village Phase II     LEED Silver®
17                UCF Visitor and Parking Information       LEED Gold®
18                                   UCF Classroom II       LEED Gold®
19                            UCF Physical Science II       LEED Gold®
20                   UCF Fraternity and Sorority Life     LEED Silver®
21                            UCF College of Medicine     LEED Silver®
22                  UCF Morgridge Intl Reading Center       LEED Gold®
23                                  UCF Greek House A       LEED Gold®
24                                  UCF Greek House B       LEED Gold®
25                                UCF Partnership III     LEED Silver®
26                                  UCF Public Safety       LEED Gold®
27                UCF Recreation & Wellness Expansion       LEED Gold®
28                                UCF Career Services       LEED Gold®
29                         UCF Performing Arts Center       LEED Gold®
30                             UCF Biomedical Science     LEED Silver®
31           UCF Laboratory and Environmental Support       LEED Gold®
32                               UCF Physical Science       LEED Gold®

In [122]:
dBL = dDfX[dDfX['LEED Status'].str.contains('Registered') == False]

In [123]:
dBL

                                         BuildingName      LEED Status
2                  UCF Downtown: Central Energy Plant       LEED Gold®
3         UCF Downtown: Dr. Phillips Academic Commons       LEED Gold®
4                         UCF Student Union Expansion  LEED Certified®
6                                 UCF CREOL Expansion       LEED Gold®
7                          UCF Band Practice Facility     LEED Silver®
8                                 UCF Dining Facility  LEED Certified®
9                   UCF Resource Management Warehouse     LEED Silver®
10                           UCF Trevor Colbourn Hall       LEED Gold®
11                       UCF District Energy Plant IV       LEED Gold®
12                                     UCF Research I       LEED Gold®
13                                         UCF Global       LEED Gold®
14                                  UCF Alumni Center       LEED Gold®
15  UCF Wayne Densch Center for Student-Athlete Le...       LEED Gold®
16                      UCF Academic Village Phase II     LEED Silver®
17                UCF Visitor and Parking Information       LEED Gold®
18                                   UCF Classroom II       LEED Gold®
19                            UCF Physical Science II       LEED Gold®
20                   UCF Fraternity and Sorority Life     LEED Silver®
21                            UCF College of Medicine     LEED Silver®
22                  UCF Morgridge Intl Reading Center       LEED Gold®
23                                  UCF Greek House A       LEED Gold®
24                                  UCF Greek House B       LEED Gold®
25                                UCF Partnership III     LEED Silver®
26                                  UCF Public Safety       LEED Gold®
27                UCF Recreation & Wellness Expansion       LEED Gold®
28                                UCF Career Services       LEED Gold®
29                         UCF Performing Arts Center       LEED Gold®
30                             UCF Biomedical Science     LEED Silver®
31           UCF Laboratory and Environmental Support       LEED Gold®
32                               UCF Physical Science       LEED Gold®

In [124]:
dBLN = dBL[~dBL.BuildingName.str.contains("Greek House")]

In [125]:
dBLN

                                         BuildingName      LEED Status
2                  UCF Downtown: Central Energy Plant       LEED Gold®
3         UCF Downtown: Dr. Phillips Academic Commons       LEED Gold®
4                         UCF Student Union Expansion  LEED Certified®
6                                 UCF CREOL Expansion       LEED Gold®
7                          UCF Band Practice Facility     LEED Silver®
8                                 UCF Dining Facility  LEED Certified®
9                   UCF Resource Management Warehouse     LEED Silver®
10                           UCF Trevor Colbourn Hall       LEED Gold®
11                       UCF District Energy Plant IV       LEED Gold®
12                                     UCF Research I       LEED Gold®
13                                         UCF Global       LEED Gold®
14                                  UCF Alumni Center       LEED Gold®
15  UCF Wayne Densch Center for Student-Athlete Le...       LEED Gold®
16                      UCF Academic Village Phase II     LEED Silver®
17                UCF Visitor and Parking Information       LEED Gold®
18                                   UCF Classroom II       LEED Gold®
19                            UCF Physical Science II       LEED Gold®
20                   UCF Fraternity and Sorority Life     LEED Silver®
21                            UCF College of Medicine     LEED Silver®
22                  UCF Morgridge Intl Reading Center       LEED Gold®
25                                UCF Partnership III     LEED Silver®
26                                  UCF Public Safety       LEED Gold®
27                UCF Recreation & Wellness Expansion       LEED Gold®
28                                UCF Career Services       LEED Gold®
29                         UCF Performing Arts Center       LEED Gold®
30                             UCF Biomedical Science     LEED Silver®
31           UCF Laboratory and Environmental Support       LEED Gold®
32                               UCF Physical Science       LEED Gold®

In [126]:
dBLN = dBLN.reset_index(drop=True)

In [127]:
dBLN

                                         BuildingName      LEED Status
0                  UCF Downtown: Central Energy Plant       LEED Gold®
1         UCF Downtown: Dr. Phillips Academic Commons       LEED Gold®
2                         UCF Student Union Expansion  LEED Certified®
3                                 UCF CREOL Expansion       LEED Gold®
4                          UCF Band Practice Facility     LEED Silver®
5                                 UCF Dining Facility  LEED Certified®
6                   UCF Resource Management Warehouse     LEED Silver®
7                            UCF Trevor Colbourn Hall       LEED Gold®
8                        UCF District Energy Plant IV       LEED Gold®
9                                      UCF Research I       LEED Gold®
10                                         UCF Global       LEED Gold®
11                                  UCF Alumni Center       LEED Gold®
12  UCF Wayne Densch Center for Student-Athlete Le...       LEED Gold®
13                      UCF Academic Village Phase II     LEED Silver®
14                UCF Visitor and Parking Information       LEED Gold®
15                                   UCF Classroom II       LEED Gold®
16                            UCF Physical Science II       LEED Gold®
17                   UCF Fraternity and Sorority Life     LEED Silver®
18                            UCF College of Medicine     LEED Silver®
19                  UCF Morgridge Intl Reading Center       LEED Gold®
20                                UCF Partnership III     LEED Silver®
21                                  UCF Public Safety       LEED Gold®
22                UCF Recreation & Wellness Expansion       LEED Gold®
23                                UCF Career Services       LEED Gold®
24                         UCF Performing Arts Center       LEED Gold®
25                             UCF Biomedical Science     LEED Silver®
26           UCF Laboratory and Environmental Support       LEED Gold®
27                               UCF Physical Science       LEED Gold®

In [128]:
dLEED = pd.concat([dBLN,ddd],axis =1)

In [129]:
#dLEED = pd.concat([dBLN,dDf3],axis =1)

In [130]:
dLEED = dLEED.rename(columns ={0:'AwardYear','BuildingName': 'Building Name'})

In [131]:
#pipes['ID']= pipes['ID'].replace({1.0:1.049,2.0: 2.067, 3.0:3.068, 4.0: 4.026, 5.0:5.047, 6.0: 6.065, 8.0: 7.981, 10.0:10.020, 12.0 : 11.938, 16.0 : 15.0, 18.0 : 16.876, 20.0 : 18.812, 24.0 : 22.624, 32.0: 30.624 , 34.0: 32.624, 36.0 : 34.5, 42.0 : 40.5})

In [132]:
#dLEED['AwardYear']=dLEED['AwardYear'].replace({'<td colspan="2">Certification awarded':'',']':''})

In [133]:
#dLEED['AwardYear'] = dLEED['AwardYear'].replace(['<', ']'], 'A')

In [134]:
dLEED['AwardYear'] = dLEED['AwardYear'].replace({'Certification awarded','A'})

In [135]:
dLEED['AwardYear'] = dLEED.AwardYear.str.extract('(\d+\.*\d*)')

In [136]:
dLEED

,Building Name,LEED Status,AwardYear
0,UCF Downtown: Central Energy Plant,LEED Gold®,2020
1,UCF Downtown: Dr. Phillips Academic Commons,LEED Gold®,2021
2,UCF Student Union Expansion,LEED Certified®,2021
3,UCF CREOL Expansion,LEED Gold®,2020
4,UCF Band Practice Facility,LEED Silver®,2018
5,UCF Dining Facility,LEED Certified®,2019
6,UCF Resource Management Warehouse,LEED Silver®,2019
7,UCF Trevor Colbourn Hall,LEED Gold®,2019
8,UCF District Energy Plant IV,LEED Gold®,2018
9,UCF Research I,LEED Gold®,2018
10,UCF Global,LEED Gold®,2016
11,UCF Alumni Center,LEED Gold®,2018
12,UCF Wayne Densch Center for Student-Athlete Le...,LEED Gold®,2017
13,UCF Academic Village Phase II,LEED Silver®,2015
14,UCF Visitor and Parking Information,LEED Gold®,2015
15,UCF Classroom II,LEED Gold®,2015
16,UCF Physical Science II,LEED Gold®,2015
17,UCF Fraternity and Sorority Life,LEED Silver®,2014
18,UCF College of Medicine,LEED Silver®,2014
19,UCF Morgridge Intl Reading Center,LEED Gold®,2014
20,UCF Partnership III,LEED Silver®,2012
21,UCF Public Safety,LEED Gold®,2012
22,UCF Recreation & Wellness Expansion,LEED Gold®,2012
23,UCF Career Services,LEED Gold®,2012
24,UCF Performing Arts Center,LEED Gold®,2012
25,UCF Biomedical Science,LEED Silver®,2010
26,UCF Laboratory and Environmental Support,LEED Gold®,2010
27,UCF Physical Science,LEED Gold®,2009

In [ ]:
dLEED.to_csv ('ucfEnergyCleanDataC',index=None)

In [137]:
#pipesB = pipes.B.str.extract('(\d+\.*\d*)')

In [138]:
#import re
#nop = re.findall(r'= \d+', d3)
#nop = re.findall(r'\d+', str(nop))
#nop = ''.join(nop)
#nop = float(nop)
#nop